# Numpy

## Creating Array

### 1-d Array

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


### 2-d Array

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3-d Array

In [4]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
